// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interfaces/repositories/datafile_repository_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataFileRepositoryInterface is a mock of DataFileRepositoryInterface interface.
type MockDataFileRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockDataFileRepositoryInterfaceMockRecorder
}

// MockDataFileRepositoryInterfaceMockRecorder is the mock recorder for MockDataFileRepositoryInterface.
type MockDataFileRepositoryInterfaceMockRecorder struct {
	mock *MockDataFileRepositoryInterface
}

// NewMockDataFileRepositoryInterface creates a new mock instance.
func NewMockDataFileRepositoryInterface(ctrl *gomock.Controller) *MockDataFileRepositoryInterface {
	mock := &MockDataFileRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockDataFileRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataFileRepositoryInterface) EXPECT() *MockDataFileRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetDatafile mocks base method.
func (m *MockDataFileRepositoryInterface) GetDatafile(filename string) (io.Reader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatafile", filename)
	ret0, _ := ret[0].(io.Reader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatafile indicates an expected call of GetDatafile.
func (mr *MockDataFileRepositoryInterfaceMockRecorder) GetDatafile(filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatafile", reflect.TypeOf((*MockDataFileRepositoryInterface)(nil).GetDatafile), filename)
}
